/****** Object:  Database [BillingCenterDb]    Script Date: 6/30/2020 3:21:27 PM ******/
CREATE DATABASE [BillingCenterDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BillingCenterDb', FILENAME = N'/var/opt/mssql/data/BillingCenterDb.mdf' , SIZE = 1024000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 0), 
 FILEGROUP [ADMINFG_bc] 
( NAME = N'adminfg_bcdb', FILENAME = N'/var/opt/mssql/data/adminfg_bcdb.ndf' , SIZE = 1024000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 0), 
 FILEGROUP [INDEXFG_bc] 
( NAME = N'indexfg_bcdb', FILENAME = N'/var/opt/mssql/data/indexfg_bcdb.ndf' , SIZE = 1024000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 0), 
 FILEGROUP [LOBFG_bc] 
( NAME = N'lobfg_bcdb', FILENAME = N'/var/opt/mssql/data/lobfg_bcdb.ndf' , SIZE = 1024000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 0), 
 FILEGROUP [OPFG_bc] 
( NAME = N'opfg_bcdb', FILENAME = N'/var/opt/mssql/data/opfg_bcdb.ndf' , SIZE = 1024000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 0), 
 FILEGROUP [STAGINGFG_bc] 
( NAME = N'stagingfg_bcdb', FILENAME = N'/var/opt/mssql/data/stagingfg_bcdb.ndf' , SIZE = 1024000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 0), 
 FILEGROUP [TYPELISTFG_bc] 
( NAME = N'typelistfg_bcdb', FILENAME = N'/var/opt/mssql/data/typelistfg_bcdb.ndf' , SIZE = 1024000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 0)
 LOG ON 
( NAME = N'BillingCenterDb_log', FILENAME = N'/var/opt/mssql/data/BillingCenterDb_log.ldf' , SIZE = 512000KB , MAXSIZE = 2048GB , FILEGROWTH = 0)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BillingCenterDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BillingCenterDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BillingCenterDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BillingCenterDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BillingCenterDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BillingCenterDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [BillingCenterDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BillingCenterDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BillingCenterDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BillingCenterDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BillingCenterDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BillingCenterDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BillingCenterDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BillingCenterDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BillingCenterDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BillingCenterDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BillingCenterDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BillingCenterDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BillingCenterDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BillingCenterDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BillingCenterDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BillingCenterDb] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [BillingCenterDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BillingCenterDb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BillingCenterDb] SET  MULTI_USER 
GO

ALTER DATABASE [BillingCenterDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BillingCenterDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BillingCenterDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BillingCenterDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [BillingCenterDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BillingCenterDb] SET QUERY_STORE = OFF
GO

ALTER DATABASE [BillingCenterDb] SET  READ_WRITE 
GO


ALTER DATABASE BillingCenterDb
SET READ_COMMITTED_SNAPSHOT ON
WITH ROLLBACK IMMEDIATE
GO 