/****** Object:  Database [ClaimCenterDB]    Script Date: 6/30/2020 3:21:27 PM ******/
CREATE DATABASE [ClaimCenterDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ClaimCenterDB', FILENAME = N'/var/opt/mssql/data/ClaimCenterDB.mdf' , SIZE = 1024000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 0), 
 FILEGROUP [ADMINFG_cc] 
( NAME = N'adminfg_ccdb', FILENAME = N'/var/opt/mssql/data/adminfg_ccdb.ndf' , SIZE = 1024000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 0), 
 FILEGROUP [INDEXFG_cc] 
( NAME = N'indexfg_ccdb', FILENAME = N'/var/opt/mssql/data/indexfg_ccdb.ndf' , SIZE = 1024000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 0), 
 FILEGROUP [LOBFG_cc] 
( NAME = N'lobfg_ccdb', FILENAME = N'/var/opt/mssql/data/lobfg_ccdb.ndf' , SIZE = 1024000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 0), 
 FILEGROUP [OPFG_cc] 
( NAME = N'opfg_ccdb', FILENAME = N'/var/opt/mssql/data/opfg_ccdb.ndf' , SIZE = 1024000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 0), 
 FILEGROUP [STAGINGFG_cc] 
( NAME = N'stagingfg_ccdb', FILENAME = N'/var/opt/mssql/data/stagingfg_ccdb.ndf' , SIZE = 1024000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 0), 
 FILEGROUP [TYPELISTFG_cc] 
( NAME = N'typelistfg_ccdb', FILENAME = N'/var/opt/mssql/data/typelistfg_ccdb.ndf' , SIZE = 1024000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 0)
 LOG ON 
( NAME = N'ClaimCenterDB_log', FILENAME = N'/var/opt/mssql/data/ClaimCenterDB_log.ldf' , SIZE = 512000KB , MAXSIZE = 2048GB , FILEGROWTH = 0)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ClaimCenterDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ClaimCenterDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ClaimCenterDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ClaimCenterDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ClaimCenterDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ClaimCenterDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [ClaimCenterDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ClaimCenterDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ClaimCenterDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ClaimCenterDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ClaimCenterDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ClaimCenterDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ClaimCenterDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ClaimCenterDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ClaimCenterDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ClaimCenterDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ClaimCenterDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ClaimCenterDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ClaimCenterDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ClaimCenterDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ClaimCenterDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ClaimCenterDB] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [ClaimCenterDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ClaimCenterDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ClaimCenterDB] SET  MULTI_USER 
GO

ALTER DATABASE [ClaimCenterDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ClaimCenterDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ClaimCenterDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ClaimCenterDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ClaimCenterDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ClaimCenterDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ClaimCenterDB] SET  READ_WRITE 
GO


ALTER DATABASE ClaimCenterDB
SET READ_COMMITTED_SNAPSHOT ON
WITH ROLLBACK IMMEDIATE
GO 