apiVersion: v1
kind: Pod
metadata:
  name: kubia-jim-liveness
spec:
  containers:
  - image: arribajim/kubia-unhealthy-time
    name: arribajim
    livenessProbe:
      httpGet:
        path: /
        port: 8080

