apiVersion: v1
kind: Pod
metadata:
  name: gw-ab-local
  namespace: guidewire-ns
  labels:
    env: local
    app: ab1003
    rel: canary
    ver: "10.3"
spec:
  containers:
  - image: arribajim/tomcat9:gw-ab_v1
    env:
    - name: JAVA_OPTS
      value: "-Dgw.ab.serverid=#batch,workqueue,scheduler,messaging,startable,ui -Dgw.server.mode=dev -Dgw.ab.env=docker -Dgw.passthrough.gw.config.external.property.file=/usr/local/tomcat/conf/external_gw.properties"
    name: ab1003    
    volumeMounts:
    - name: tmpvol
      mountPath: /tmp
    ports:
        - containerPort: 8080
          protocol: TCP
    readinessProbe:
        exec:
            command:
            - curl
            - http://localhost:8080/ab/ping
  volumes:
  - name: tmpvol
    emptyDir: {}