apiVersion: v1
kind: Pod
metadata:
  name: contact-manager
spec:
  containers:
  - name: batch-gw
    image: arribajim/tomcat9:ab1003
    volumeMounts:
    - name: tmpvol
      mountPath: /tmp
    ports:
        - containerPort: 8280
          protocol: TCP
  volumes:
  - name: tmpvol
    emptyDir: {}

