apiVersion: v1
kind: ReplicationController
metadata:
  name: gw-ab-rc
  namespace: guidewire-ns
  labels:
    env: local
    app: ab1003
    rel: canary
    ver: "10.3"

spec:
  replicas: 2
  selector:
    app: ab1003  #valor mas importante, pivotea el rc para identificar la cantidad de pods
  template:
    metadata:
      labels:
        app: ab1003 #label de control
    spec:
      containers:
      - image: arribajim/tomcat9:gw-ab_v1
        env:
        - name: JAVA_OPTS
          value: "-Dgw.ab.serverid=#workqueue,scheduler,messaging,startable,ui -Dgw.server.mode=dev -Dgw.ab.env=docker -Dgw.passthrough.gw.config.external.property.file=/usr/local/tomcat/conf/external_gw.properties"
        name: ab1003    
        volumeMounts:
        - name: tmpvol
          mountPath: /tmp
        ports:
            - containerPort: 8080
              protocol: TCP
      volumes:
      - name: tmpvol
        emptyDir: {}
