apiVersion: v1
kind: Pod
metadata:
  name: gw-ab
  namespace: guidewire-ns
  Annotations:
    note1: "esta nota es un ejemplo, checar si funciona al crear el pod"
  labels:
    env: docker
    app: ab
    rel: canary
    ver: 10.3
spec:
  containers:
  - image: arribajim/tomcat9:ab1003 #change image for app
    name: ab1003
    livenessProbe:
      httpGet:
        path: /
        port: 8280
        initialDelaySeconds: 600        
    volumeMounts:
    - name: tmpvol
      mountPath: /tmp
    ports:
        - containerPort: 8280
          protocol: TCP
  volumes:
  - name: tmpvol
    emptyDir: {}
